### ISSUE TITLE
Guide Todo app HTML

### ISSUE THREAD

**Issue by MoAgamia** [MoAgamia/SE-Boot-Camp#14]
Guides for HTML.

- [ ] Create a new page called "HTML" on Wiki
- [ ]  Write guide for HTML
- [ ]  Add references to guide
