### ISSUE TITLE
Guide Todo app JavaScript

### ISSUE THREAD

**Issue by MoAgamia** [MoAgamia/SE-Boot-Camp#16]
Guides for JavaScript

- [ ] Create a new page called "JS" on Wiki.
- [ ]  Write guide for JS
- [ ]  Add references to guide
