### ISSUE TITLE
Guide Todo app Backend

### ISSUE THREAD

**Issue by MoAgamia** [MoAgamia/SE-Boot-Camp#17]
Guides for Backend

- [ ] Create a new page called "Backend" on Wiki.
- [ ]  Write guide for Backend
- [ ]  Add references to guide
