### ISSUE TITLE
Guide Todo app Angular

### ISSUE THREAD

**Issue by MoAgamia** [MoAgamia/SE-Boot-Camp#18]
Guides for Angular

- [ ] Create a new page called "Angular" on Wiki.
- [ ]  Write guide for Angular
- [ ]  Add references to guide
