### ISSUE TITLE
Guide Todo app Vue.js

### ISSUE THREAD

**Issue by MoAgamia** [MoAgamia/SE-Boot-Camp#19]
Guides for Vue.js

- [ ] Create a new page called "Vue.js" on Wiki.
- [ ]  Write guide for Vue.js
- [ ]  Add references to guide
